name: auto-merge

permissions: write-all
  
on:
  pull_request_target:
    branches: [ master ]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fastify/github-action-merge-dependabot@v3
