name: Dockerhub build and push

on:
  workflow_run:
    workflows: ["Lint the API", "Run Unit tests"]
    types:
      - completed

concurrency: 
  group: $"{{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/titanscouting/red-alliance-api/red-alliance-api:latest