# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build documentation

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: Run typedoc to generate docs page
      run: yarn run doc
    - name: git add
      run: git add docs/
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--no-verify --signoff'
        commit_message: Build documentation
        commit_user_name: Documentation Builder
        commit_user_email: titanscout2022@gmail.com
        commit_author: Documentation Builder <titanscout2022@gmail.com>
        branch: documentation
        file_pattern: docs/*
        push_options: '--force'
        skip_dirty_check: true