name: Build and deploy by @${{ github.actor }}

on:
  push:
    branches: [ master ]

concurrency: 
  group: $"{{ github.ref }}"
  cancel-in-progress: true

jobs:
  unit:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2
    - run: yarn
    - name: Check typescript compiles
      run: yarn build
    - name: Run unit tests and output to lcov
      run: yarn run coverage
      env:
        REDALLIANCEDBKEY: ${{ secrets.REDALLIANCEDBKEY }}
        TRA_CLIENTID: ${{secrets.TRA_CLIENTID}}
        TRA_CLIENTSECRET: ${{secrets.TRA_CLIENTSECRET}}
        TBA_KEY: ${{secrets.TBA_KEY}}
        TRA_DISABLE_APIKEY_CHECKS: true
        TRA_TESTING: true
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: "Create and Push Docker image"
    needs: unit
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/titanscouting/red-alliance-api/red-alliance-api:latest

