# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Unit tests (PR)

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2
    - run: yarn
    - name: Check typescript compiles
      run: yarn build
    - name: Run unit tests and output to lcov
      run: yarn run coverage
      env:
        REDALLIANCEDBKEY: ${{ secrets.REDALLIANCEDBKEY }}
        TRA_CLIENTID: ${{secrets.TRA_CLIENTID}}
        TRA_CLIENTSECRET: ${{secrets.TRA_CLIENTSECRET}}
        TBA_KEY: ${{secrets.TBA_KEY}}
        TRA_DISABLE_APIKEY_CHECKS: true
        TRA_TESTING: true
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


